engines:
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - packages/*/lib/**
exclude_paths:
- "packages/*/test/fixtures/**/*"
