language: node_js
node_js:
  - "7"
  - "6"
  - "4"
script: "find packages -type d -depth 1 -execdir npm install \\; && npm run ci"
after_script: "npm install codecov && cat ./coverage/lcov.info | codecov"
