language: node_js
node_js:
  - "7"
  - "6"
  - "4"
script: "PATH=`echo $PATH | sed -e 's/:\\.\\/node_modules\\/\\.bin//'` find packages -maxdepth 1 -type d -execdir npm install \\; && npm run ci"
after_script: "npm install codecov && cat ./coverage/lcov.info | codecov"
